# .github/workflows/tests.yaml
name: Tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: mamba-org/setup-micromamba@v1
      # https://github.com/mamba-org/setup-micromamba
      with:
        init-shell: bash
    - uses: actions/setup-python@v4
      with:
        python-version: 3.11
        architecture: x64
    - run: pip install nox>=2022.11.21
    - name: Run Nox
      run: nox 
      shell: micromamba-shell {0}
